name: Continuous Integration

on:
  push:
  pull_request_target:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run lint
        run: |
          yarn lint
      - name: Run tests and check coverage
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          yarn testCoverage
